name: Compare spec to docs
on:
  workflow_dispatch:
jobs:
  compare:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        working-directory: ./_docmatch
        run: pip install .
      - name: Fetch docs
        working-directory: ./_docmatch
        run: curl -L https://spoonacular.com/food-api/docs > docs.html
      - name: Compare
        working-directory: ./_docmatch
        run: python src/docmatch.py
